all:
  hosts:
    cobalt:
      ansible_connection: local
      ansible_host: localhost
    titan:
      ansible_connection: local
      ansible_host: localhost
    neutron:
      ansible_connection: local
      ansible_host: localhost
