(setq make-backup-files nil)
(setq inhibit-startup-message t)
(setq-default indent-tabs-mode nil)
(blink-cursor-mode 0)
(show-paren-mode t)
(setq visible-bell t)
(add-hook 'before-save-hook 'delete-trailing-whitespace)
(if (boundp 'menu-bar-mode) (menu-bar-mode 0))
(if (boundp 'tool-bar-mode) (tool-bar-mode 0))
(if (boundp 'scroll-bar-mode) (scroll-bar-mode 0))
